### ISSUE TITLE
Versioning of a specific commit of the specification as a predraft

### ISSUE THREAD

**Issue by Sakurann** [w3c-ccg/vc-status-list-2021#32]
Could we please give commit [343b8b5](https://github.com/w3c-ccg/vc-status-list-2021/tree/343b8b59cddba4525e1ef355356ae760fc75904e) a version (for example v0.0.1-predraft) and publish it? Few implementations are using this commit of this document in production and would like to be able to refer our clients, etc. to one document. The plan is to move to the latest version of StatusList2021 once published, but while some non-backward compatible changes are being made, it would be really appreciated if we could version a commit above as an interim solution. Happy to do a PR. Thanks!

**Comment by yanicakj** [comment]
Hi @msporny @OR13, would it be okay to give this commit a version & publish it as "predraft"? It seems we are unable to add tags via an external PR [after some research](https://stackoverflow.com/questions/12278660/adding-tags-to-a-pull-request) unfortunately.

**Comment by msporny** [comment]
Yep, looking into it now.

**Comment by msporny** [comment]
Done: https://github.com/w3c-ccg/vc-status-list-2021/releases/tag/v0.0.1

**Comment by Sakurann** [comment]
Is the version available as a hosted URL? I can't seem to find it...

**Comment by yanicakj** [comment]
Thanks @msporny ! Btw do you know if it's possible to view this commit version at a hosted URL? Or is the only option for us to clone, checkout tag, & view index.html locally?

**Comment by msporny** [comment]
> Thanks @msporny ! Btw do you know if it's possible to view this commit version at a hosted URL? Or is the only option for us to clone, checkout tag, & view index.html locally?

Unless we create a static copy, only the latter. We could create a static copy, but we try to not do that because there is no consensus that this particular version is something the community wants to convey to the outside world as stable (I understand that Microsoft and Workday do have consensus on that point).

What you could is generate a static copy and publish it somewhere that you have control over, the current document license allows you to do that, IIUC.
